apiVersion: v2
name: aapb
description: American Archive of Public Broadcasting Helm Chart
version: 0.1.2
dependencies:
- name: app-template
  version: 4.4.0
  repository: https://bjw-s-labs.github.io/helm-charts/
home: https://wgbh-mla.github.io/aapb-deploy/
icon: https://wgbh-mla.github.io/aapb-deploy/latest/assets/aapb-logo.png
keywords:
  - remix
  - archive
maintainers:
  - name: Harpo
    email: ryan_harbert@wgbh.org
sources:
  - https://github.com/WGBH-MLA/aapb-deploy

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump app-template dependency to v4.4.0
      links:
      - name: GitHub Release
        url: https://github.com/WGBH-MLA/aapb-deploy/releases/tag/aapb-0.1.2
    - kind: changed
      description: Update default AAPB_API_URL and ES_URL in values.yaml
